version: '3.8'

services:
    # PHP Service
    php:
        user: "${UID:-1000}:${GID:-1000}"
        build:
            context: .              # Build context is current directory
            dockerfile: docker/php/Dockerfile
        container_name: php83_app # Name our container
        working_dir: /var/www
        volumes:
            - ./:/var/www   # Mount our source code
        networks:
            - app-network          # Connect to our network
        environment:
            PHP_IDE_CONFIG: serverName=Docker # For Xdebug
        # Make container restart unless stopped manually
        restart: unless-stopped

    # Nginx Service
    nginx:
        image: nginx:latest      # Use official Nginx image
        container_name: nginx_app
        ports:
            - "80:80"           # Map port 8080 on our PC to 80 in container
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php                 # Wait for PHP container
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge          # Standard Docker network type
